name: Release

on:
  release:
    types:
      - published

jobs:
  osx:
    runs-on: macos-latest
    steps:
      - name: Get tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF##*/}
          echo ::set-output name=tag::${TAG}

      - name: build
        run: |
          set -x
          
          brew install oras

          # homebrew doesn't use v, just a number triplet
          _version=${{ steps.tagName.outputs.tag }}
          _version=${_version:1}

          echo ref ${GITHUB_REF}
          echo ref_name ${GITHUB_REF_NAME}
          
          # AMD64 is not supported beyond 12.6
          oras pull ghcr.io/homebrew/core/envoy:${_version} --platform "darwin/amd64:macOS 12.6"
          tar --extract \
              --file envoy--${_version}.monterey.bottle.tar.gz \
              --directory . \
              --strip-components=3 \
              envoy/${_version}/bin/envoy
          mv -f envoy envoy-darwin-amd64

          oras pull ghcr.io/homebrew/core/envoy:${_version} --platform "darwin/arm64:macOS 13"
          tar --extract \
              --file envoy--${_version}.arm64_ventura.bottle.tar.gz \
              --directory . \
              --strip-components=3 \
              envoy/${_version}/bin/envoy
          mv -f envoy envoy-darwin-arm64

          shasum -a 256 envoy-darwin-amd64 > envoy-darwin-amd64.sha256
          shasum -a 256 envoy-darwin-arm64 > envoy-darwin-arm64.sha256

      - name: Upload artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release -R pomerium/envoy-binaries upload ${{ steps.tagName.outputs.tag }} envoy-darwin-*

  linux:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.18.x

      # We need api 1.41 to override platform
      - name: Install docker stable
        uses: docker-practice/actions-setup-docker@5d9a5f65f510c01ec5f0bd81d5c95768b1ec032a
        with:
          docker_channel: stable
          docker_version: 20.10

      - name: Set up Docker
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Get tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF##*/}
          echo ::set-output name=tag::${TAG}

      - name: Run fetchenvoy
        working-directory: fetchenvoy
        run: |
          go run . ${{steps.tagName.outputs.tag}}

      - name: shasum
        working-directory: fetchenvoy
        run: |
          shasum -a 256 envoy-linux-amd64 > envoy-linux-amd64.sha256
          shasum -a 256 envoy-linux-arm64 > envoy-linux-arm64.sha256

      - name: Upload artifacts to release
        working-directory: fetchenvoy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.tagName.outputs.tag }} envoy-*
