name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF##*/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

      - name: Install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install oras

      - name: fetch and upload envoy (linux)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux arm64
          gh release upload ${{ steps.tagName.outputs.tag }} bin/envoy-linux-* --clobber

      - name: fetch and upload our built envoy (darwin)
        env:
          GH_TOKEN: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
        run: |
          gh release download -R pomerium/envoy-build ${{ steps.tagName.outputs.tag }}
          gh release upload ${{ steps.tagName.outputs.tag }} envoy-darwin-* --clobber
