name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF##*/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55

      - name: Install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install oras

      - name: fetch envoy
        run: |
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} darwin amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} darwin arm64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux arm64

      - name: Upload artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.tagName.outputs.tag }} bin/envoy-* --clobber
