name: Release

on:
  workflow_dispatch:
    inputs:
      envoyVersion:
        description: "Envoy Version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

      - name: Install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install oras

      - name: fetch envoy
        run: |
          ./scripts/fetch-envoy ${{ github.event.inputs.envoyVersion }} darwin amd64
          ./scripts/fetch-envoy ${{ github.event.inputs.envoyVersion }} darwin arm64
          ./scripts/fetch-envoy ${{ github.event.inputs.envoyVersion }} linux amd64
          ./scripts/fetch-envoy ${{ github.event.inputs.envoyVersion }} linux arm64

      - name: Upload artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.inputs.envoyVersion }} bin/envoy-*
