name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF##*/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install oras
          echo "$(/home/linuxbrew/.linuxbrew/bin/brew --prefix)/bin" >> $GITHUB_PATH

      - name: fetch and upload envoy (linux)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux arm64
          gh release upload ${{ steps.tagName.outputs.tag }} bin/envoy-linux-* --clobber

      - name: fetch and upload envoy (darwin)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} darwin amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} darwin arm64
          gh release upload ${{ steps.tagName.outputs.tag }} bin/envoy-darwin-* --clobber
